name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2
      with:
       fetch-depth: 2

    - name: Pre-CI checks
      env:
        GITHUB_COMMIT_URL: ${{ github.event.pull_request.commits_url }}
        GITHUB_PUSH_BEFORE: ${{ github.event.push.before }}
        GITHUB_PUSH_AFTER: ${{ github.event.push.head }}
        COMMIT_RANGE: ""
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        go get -u github.com/vbatts/git-validation
        go get -u github.com/kunalkushwaha/ltag
        pushd ..; git clone https://github.com/containerd/project; popd
        echo "PR commits: ${GITHUB_COMMIT_URL}"
        echo "push before: ${GITHUB_PUSH_BEFORE}"
        echo "push after: ${GITHUB_PUSH_AFTER}"
        if [ -z "${GITHUB_COMMIT_URL}" ]; then
          COMMIT_RANGE="${GITHUB_PUSH_BEFORE}..${GITHUB_PUSH_AFTER}"
        else
          COMMIT_RANGE=$(curl ${GITHUB_COMMIT_URL} | jq -r '.[0].parents[0].sha +".."+ .[-1].sha')
        fi
        git-validation -range "${COMMIT_RANGE}" -v -run DCO,short-subject,dangling-whitespace
        ../project/script/validate/fileheader ../project/

    - name: Test
      if: success()
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    
    - name: Codecov
      if: success()
      run: bash <(curl -s https://codecov.io/bash)
        
