name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Pre-CI checks
      run: |
        go get -u github.com/vbatts/git-validation
        go get -u github.com/kunalkushwaha/ltag
        pushd ..; git clone https://github.com/containerd/project; popd
        DCO_VERBOSITY=-q ../project/script/validate/dco
        ../project/script/validate/fileheader ../project/

    - name: Test
      if: success()
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    
    - name: Codecov
      if: success()
      run: bash <(curl -s https://codecov.io/bash)
        
