name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2
      with:
       fetch-depth: 3
      
    - name: Pre-CI checks
      env:
        GITHUB_COMMIT_URL: ${{ github.event.pull_request.commits_url }}
        COMMIT_RANGE: ""
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        go get -u github.com/vbatts/git-validation
        go get -u github.com/kunalkushwaha/ltag
        pushd ..; git clone https://github.com/containerd/project; popd
        COMMIT=$(jq -r '.after' ${GITHUB_EVENT_PATH})
        if [ -z "${GITHUB_COMMIT_URL}" ]; then
          COMMIT_RANGE=$(jq -r '.before +".."+ .after' ${GITHUB_EVENT_PATH})
        else
          COMMIT_RANGE=$(curl ${GITHUB_COMMIT_URL} | jq -r '.[0].parents[0].sha +".."+ .[-1].sha')
        fi
        echo "range: ${COMMIT_RANGE}"
        git checkout "${COMMIT}"
        git-validation -range "${COMMIT_RANGE}" -D -v -run DCO,short-subject,dangling-whitespace
        ../project/script/validate/fileheader ../project/

    - name: Test
      if: success()
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    
    - name: Codecov
      if: success()
      run: bash <(curl -s https://codecov.io/bash)
        
